// <auto-generated />
using System;
using BookTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTrackerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204190814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTrackerAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishedReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleBooksId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2025, 12, 31, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2128),
                            Author = "J.R.R. Tolkien",
                            Description = "A fantasy adventure about Bilbo Baggins",
                            FinishedReadingDate = new DateTime(2026, 1, 5, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2181),
                            Genres = "Fantasy,Adventure",
                            GoogleBooksId = "sample1",
                            PageCount = 310,
                            Rating = 5,
                            Review = "An absolute classic!",
                            Status = 2,
                            Title = "The Hobbit",
                            UpdatedAt = new DateTime(2026, 1, 5, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2179)
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2026, 1, 25, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2190),
                            Author = "George Orwell",
                            Description = "A dystopian social science fiction novel",
                            Genres = "Science Fiction,Dystopian",
                            GoogleBooksId = "sample2",
                            PageCount = 328,
                            StartedReadingDate = new DateTime(2026, 1, 30, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2194),
                            Status = 1,
                            Title = "1984",
                            UpdatedAt = new DateTime(2026, 1, 30, 14, 8, 13, 509, DateTimeKind.Local).AddTicks(2192)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
